name: Python CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # Триггер на пуш в main
  pull_request:
    branches: [ "main" ]  # И на PR в main
  release:
    types: [created]      # Триггер при создании тега (релиза)

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub-hosted runner
    steps:
      - uses: actions/checkout@v4  # Клонируем репозиторий
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: pytest  # Запускаем тесты

  build-docker:
    needs: test  # Зависит от успешного выполнения job "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            your-docker-username/your-app:latest
            your-docker-username/your-app:${{ github.ref_name }}